[default]

env = "prod"
container_env = false
log_level = "DEBUG"

api_title = "MedCab API"
api_description = "The backend API for MedCab."
api_version = "0.1.0"
api_port = 8000
api_debug = false

db_type = "sqlite"
db_host = ""
db_username = ""
db_password = ""
db_port = ""
db_database = ".db/demo.sqlite"

[dev]

env = "dev"
log_level = "DEBUG"

api_title = "MedCab API - DEV"
api_version = "0.1.0-a"
api_debug = true

db_type = "sqlite"
db_host = ""
db_username = ""
db_password = ""
db_port = ""
db_database = ".db/demo.sqlite"

api_port = 8086

[prod]
