version: "3.8"

networks:
  proxy_net:
    driver: bridge

volumes:
  nginx_cache:

services:

  api:
    container_name: medcab_api
    restart: unless-stopped
    build:
      context: ./apps/medcab-backend
      dockerfile: ${MEDCAB_BACKEND_DOCKERFILE:-Dockerfile}
      target: ${MEDCAB_BACKEND_DOCKERFILE_BUILD_TARGET:-prod}
    working_dir: /app
    command: python start_server.py
    volumes:
      - ${MEDCAB_BACKEND_APP_DIR:-./apps/medcab-backend/src}:/app
    ## Comment port definitions if using a proxy container
    # ports:
    #   - ${MEDCAB_BACKEND_HOST_PORT:-5000}:${MEDCAB_BACKEND_APP_PORT:-5000}
    environment:
      DYNACONF_ENV: ${MEDCAB_BACKEND_ENV:-prod}
      DYNACONF_CONTAINER_ENV: true
      DYNACONF_LOG_LEVEL: ${MEDCAB_BACKEND_LOG_LEVEL:-INFO}
      DYNACONF_APP_NAME: ${MEDCAB_BACKEND_APP_NAME:-MedCab}
      DYNACONF_APP_DESCRIPTION: ${MEDCAB_BACKEND_DESCRIPTION:-Default description}
      DYNACONF_APP_VERSION: ${MEDCAB_BACKEND_VERSION:-0.1.0}
      DYNACONF_APP_DEBUG: ${MEDCAB_BACKEND_DEBUG:-false}
      DYNACONF_APP_HOST: ${MEDCAB_BACKEND_APP_HOST:-0.0.0.0}
      DYNACONF_APP_PORT: ${MEDCAB_BACKEND_APP_PORT:-5000}
      DYNACONF_APP_SECRET_KEY: ${MEDCAB_BACKEND_APP_SECRET}
    # healthcheck:
    #   test: curl --fail http://api:5000/health
    #   interval: 5m
    #   timeout: 10s
    #   retries: 5
    #   start_period: 10s
    ## Uncomment if using a proxy container
    networks:
      - proxy_net

  ## Nginx
  proxy:
    image: nginx:latest
    container_name: medcab_proxy
    restart: unless-stopped
    # env_file: ./env_files/nginx_proxy.env
    volumes:
      - ${NGINX_CONF_DIR:-./apps/proxy/nginx/nginx.conf}:/etc/nginx/nginx.conf
      - ${NGINX_SITES_ENABLED_DIR:-./apps/proxy/nginx/conf/sites-enabled}:/etc/nginx/sites-enabled
      - ${NGINX_CONF_EXTRA_DIR:-./apps/proxy/nginx/conf/extra}:/etc/nginx/extra
      - ${NGINX_LOGS_DIR:-./apps/proxy/nginx/logs}:/var/log/nginx/
      - ${NGINX_CACHE_DIR:-nginx_cache}:/data/nginx/cache
    ports:
      - ${NGINX_HTTP_PORT:-80}:80
    environment:
      BACKEND_SERVER: ${NGINX_BACKEND_SERVER:-127.0.0.1}
    networks:
      - proxy_net
