"""${commit_msg}

Revision ID: ef9ed7eceb70
Revises: 82d0c7618db8
Create Date: 2023-12-10 21:36:41.000883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9ed7eceb70'
down_revision: Union[str, None] = '82d0c7618db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('weight', sa.Float(asdecimal=True, decimal_return_scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'weight')
    # ### end Alembic commands ###
